Repository puppetlabs/puppetlabs-inifile, pull requests merged in 2018-12, with the labels that each got.

#316 pdksync - pdksync_heads/master-0-gbf720df
  .gitattributes
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#315 (MODULES-8142) - Addition of support for SLES 15
  .sync.yml
  Gemfile
  metadata.json
Labels: feature

#320 pdksync - (FM-7655) Fix rubygems-update for ruby < 2.3
  .travis.yml
  metadata.json
Labels: bugfix
