Repository puppetlabs/puppetlabs-inifile, pull requests merged in 2019-11, with the labels that each got.

#362 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#363 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#364 MODULES-10081 - Release version 4.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#365 (MODULES-10082) - Release Merge back v4.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#366 (FM-8689) - Addition of Support for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#367 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  Gemfile
  appveyor.yml
  metadata.json
Labels: maintenance
