Repository puppetlabs/puppetlabs-inifile, pull requests merged in 2022-03, with the labels that each got.

#468 pdksync - (FM-8922) - Add Support for Windows 2022
  metadata.json
Labels: feature

#469 (MODULES-11290) Add note about create_ini_settings
  README.md
Labels: maintenance

#471 pdksync - (GH-iac-334) Remove Support for Ubuntu 14.04/16.04
  metadata.json
Labels: bugfix

#472 pdksync - Add labeller and stale GHA workflows
  .github/workflows/labeller.yml
  .github/workflows/stale.yml
Labels: maintenance
